import requests
import json
from pprint import pprint

# url generated by Trivia API for 10 questions from the General Knowledge category
url = "https://opentdb.com/api.php?amount=10&category=9"

# response variable
response = requests.get(url)

# pprint json to see content in a readable format
pprint(response.json())

# write content into a json file to use as reference in the main file for the app
with open("trivia.json", "w") as f:
    json.dump(response.json(), f, indent=4)